### ISSUE TITLE
Android Share API 报错

### ISSUE THREAD

**Issue by rickychan0611** [Hector-Zhuang/native-wechat#10]
所有 Share API 都出现以下画面
![Screenshot_20221206-085328_WeChat](https://user-images.githubusercontent.com/33400559/205982115-22cf527e-c309-4d19-b1da-56a230ece3e0.jpg)

**Comment by Hector-Chong** [comment]
这个问题似乎没有在我的设备上出现，请提供相应的 API 调用代码。

It doesn't seem to occur on my device. Please provide the code reproducing this issue.
