### ISSUE TITLE
requestPayment调用后没有返回结果

### ISSUE THREAD

**Issue by wangminhua-fe** [Hector-Zhuang/native-wechat#54]
问题：requestPayment调用，支付成功后，没有监听到微信返回结果信息，源码
    notification.once('PayResp', (error, response) => {
      if (error) {
        return reject(error);
      }

      return resolve(response);
    });

请大佬帮忙看看呢

**Comment by 616151371** [comment]
你好，怎么获取响应的，要配置文件吗

**Comment by xinKyy** [comment]
您好，请问您如何解决的？
